### ISSUE TITLE
Transfer any used Icon into an Style xaml

### ISSUE THREAD

**Issue by SonicYeager** [CookAperture/MusicPlayer#1]
# ToDo

- [x] move icon paths to an Icon.xaml
- [x] reconnect the icons to the controls
- [x] fill the Icon.xaml with soon to expect icons
