### ISSUE TITLE
Finish Dummy PlayPause

### ISSUE THREAD

**Issue by SonicYeager** [CookAperture/MusicPlayer#2]
# ToDo

- [ ] flow design - design this feature
- [ ] adjust interfaces
- [ ] write some dummy sound output in backend - flow design
- [ ] connect properly to ui
