### ISSUE TITLE
Move SongCover Control into UserControl

### ISSUE THREAD

**Issue by SonicYeager** [CookAperture/MusicPlayer#3]
# ToDo

- [x] Move Code
- [x] reconnect in xaml
- [x] write Interface and Implement it into UserControl
- [x] write Connect ExtensionMethod
