### ISSUE TITLE
Add UI response to errors/exception

### ISSUE THREAD

**Issue by SonicYeager** [CookAperture/MusicPlayer#30]
# ToDo[Tasklist]/Statement/Question

- [x] design/implement notification
- [x] design/implement error dialog
- [x] design/implement suitable way to generate dialog from custom exceptions

# Description

To be as modular and nifty as possible exceptions should also be used to inform the user about an bad state and eventually handle it and or let the user decide how to deal with it. 
Using Dialogs and or notifications an exception has to hold information to be helpful. Thus also meaning a lambda to handle the issue, and simultaneously informing the user. 
Or requesting a dialog that triggers one or more other lambdas that will handle an misstate.

**Comment by SonicYeager** [comment]
A bit more YAGNI and KISS conform approach done;
