### ISSUE TITLE
Add Caching to MediaListInteractor

### ISSUE THREAD

**Issue by SonicYeager** [CookAperture/MusicPlayer#32]
# ToDo

- [ ] Design Caching logic (may the Miro board help out)
- [ ] Implement prototype in medialist
- [ ] Repeat until it feels perfect

# Description
Due to lots of audiofiles -> 2000+ it takes time to scan for all of them from the root. If paths or even the whole meta data gets cached. (As file, serialized is probably the fastet, but try it out.)
