### ISSUE TITLE
Rework MediaListUI

### ISSUE THREAD

**Issue by SonicYeager** [CookAperture/MusicPlayer#34]
# ToDo

- [ ] Use selected AudioFileCover as Background but blurry
- [ ] Orientate on Groovy or Spotify for the list styling
- [ ] add a bit more meta data

**Comment by SonicYeager** [comment]
Maybe look into something like so: https://gist.github.com/superic/8165746
Hopefully support for similar arrives in Avalonia sooner or later!
