### ISSUE TITLE
Drag'n'Drop for AudioFiles

### ISSUE THREAD

**Issue by SonicYeager** [CookAperture/MusicPlayer#35]
# ToDo

- [ ] decide where and when drag to drop
- [ ] how to be implemented
- [ ] prototype (settings may be a good starting point)

# Motivation

quality of life for the user, and maybe an intuitive feature for more than one occasion.
