### ISSUE TITLE
Add Support for more codecs

### ISSUE THREAD

**Issue by SonicYeager** [CookAperture/MusicPlayer#37]
# ToDo[Tasklist]/Statement/Question

- [ ] add FLAC support
- [ ] add M4A support
- [ ] add MP4 support
- [ ] add WEBM support
- [ ] add WMA support

# Description

the more audio files supported the more users/enjoyment is possible. :)
